import Head from 'next/head';
import Image from 'next/legacy/image';
import Layout from '../components/Layout';
import profilePic from "../../public/images/profile/Rahul2.png"
import TypeWriter from 'typewriter-effect';
import TransitionEffect from '@/components/Transition';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Rahul Bagga Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
      <main className='flex items-center text-light w-full min-h-screen'>
        <Layout className='pt-50 ' >
          <div className="flex flex-col justify-center items-center w-full lg:flex-col relative bottom-3">
            <div className="relative rounded-full w-80 h-80 flex right-[25%] mt-10 overflow-hidden sm:relative sm:right-[1%] ">
              <Image 
                src={profilePic} 
                alt="profile" 
                layout ="fill" 
                objectFit='cover'
                priority
                sizes="(max-width: 768px) 100vw,
                        (max-width: 1200px) 50vw,
                        100vw"
              />
            </div>
            <div className='w-4/5 sm:w-1/2 mt-5 flex flex-col items-center'>
              <h1 className='my-1 text-5xl sm:text-2xl md:text-5xl text-gray-500 font-semibold font-mono relative bottom-80 left-60 sm:bottom-[10%] sm:left-[0.3%]'>Rahul &#8226; &#9794;</h1>

              <h1 className='my-2 text-5xl sm:text-xl md:text-5xl font-bold relative bottom-80 left-60 sm:relative sm:bottom-[10%] sm:left-[1%]'>
                <TypeWriter
                  options={{
                    strings: ['Front-End Dev', 'Back-End Dev', 'Game Dev'],
                    autoStart: true,
                    loop: true,
                  }}
                />
              </h1>
              <p className=' font-medium text-center text-lg sm:text-base relative bottom-72 left-60 sm:relative sm:top-1 sm:left-[1%]'>
                As a Software Developer,<br/>
                 I'm learning and experimenting to develop new ideas.
              </p>
              <p className='font-medium text-lg text-center relative bottom-72 left-60 sm:text-base sm:relative sm:top-3 sm:left-[1%]'>Explore my abilities in the latest projects.</p>

            </div>
          </div>
        </Layout>
      </main>
    </div>
  );
}
