import Head from 'next/head';
import Typewriter from 'typewriter-effect';
import Image from 'next/legacy/image';
import Rahul from '../Images/Me.png';
import Navbar from '../../components/Navbar';



export default function Home() {
  return (
    <div>
      <Head>
        <title>Rahul Bagga Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel='stylesheet'/>
    
      </Head>
      <Navbar />
      <main>
      <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 flex mr-auto ml-auto mt-20 overflow-hidden">
          <Image src = {Rahul} layout ="fill" objectFit='cover' />
        </div>
        <p className="relative  text-center text-5xl mt-7 font-bold">Portfolio Pending</p>

        <h1 className=' relative font-bold text-5xl text-center mt-5'>
          <Typewriter 
            options={{
              strings: [
                ". . .",
              ],
              autoStart: true,
              loop: true,
            }}
          />
        </h1>
      </main>
    </div>
  )
}
