
import Layout from "../components/Layout"
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import Game from "../../public/images/project/GameImg.png";
import TextAnimation from "../components/TextAnimation";
import { GitHubIcon } from "../components/Icons";




const Project = ({ type, title, summary, img, link, github }) => {
  return (

    <article className="w-full flex items-center justify-between rounded-3xl border-4 border-solid border-light bg-dark overflow-hidden relative top-10 "> 
    <div className="w-1/2 overflow-hidden rounded-lg">
        <Image src={img} alt={title} className="w-full h-auto"/>
    </div>

    <div className="w-1/2 flex flex-col items-start justify-between pl-16 relative right-10">
        <span className="font-medium text-xl">{type}</span>
            <h2 className="my-2 w-full text-left text-4xl font-bold">{title}</h2>

        <p className="my-2 font-medium text-light">{summary}</p>
        <div className="mt-2 flex items">
        <Link href={github} target="_blank" className="w-10"> <GitHubIcon/> </Link>
        <Link href={link} target="_blank" className="ml-4  bg-light text-dark p-2 px-6 text-lg font-semibold rounded-lg">Download</Link>
 
        </div>
    </div>
</article>
)
}

const projects = () => {
  return (
    <>
      <Head>
        <title>Rahul | Project</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
   
      <main className="w-full mb-16 flex flex-col items-center justify-center dark:text-light">
        <Layout>
          <TextAnimation
            text="Have Fun While Developing!"
            className="mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl"
            />
          <div className="grid grid-cols-12 gap-24 gap-y-32 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0">
            <div className="col-span-12">
              <Project
                type="Unity Game"
                title="Retro Asteroids Shooter"
                summary="A Unity Game made for a college assignment which was inspired by the original game Asteroids.
                To access the game, you need extract the downloaded zip file then click on the My Project.exe file to play"
                
                img={Game} 
                link="/Build.zip"
                github="https://github.com/MonsieurR05/Unity-Game"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default projects;
